name: "provision-with-micromamba"
description: "provision a CI instance using micromamba"
branding:
  icon: "chevrons-right"
  color: "green"
inputs:
  environment-file:
    description: "the environment.yml file for the conda environment"
    required: true
    default: environment.yml
  environment-name:
    description: "the name of the conda environment (defaults to name from the environment.yml file)"
    required: false
  micromamba-version:
    description: 'version of micromamba to use (default: 0.9.2). Use "latest" for bleeding edge.'
    required: false
    default: "latest"
  extra-specs:
    description: "extra specifications to install (defaults is empty)"
    required: false
    default: ""
  channel-priority:
    description: 'Accepts values of "strict", "flexible", and "disabled". The default value is "strict".'
    required: false
    default: "strict"

runs:
  using: "node12"
  main: "dist/index.js"
